version: '3.8'

services:
  backend:
    build: ./pingpong-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  frontend:
    build: ./pingpong-app
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    environment:
      - REACT_APP_API_URL=http://localhost:3000
    depends_on:
      - backend
    restart: unless-stopped 